"""add_supplier_scores_final_v2

Revision ID: 0ed0fc3b949f
Revises: ba6b7c0dea80
Create Date: 2026-02-18 23:19:15.544916+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ed0fc3b949f'
down_revision: Union[str, None] = 'ba6b7c0dea80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('price_consistency_score', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('delivery_speed_score', sa.Float(), nullable=True))
    op.add_column('suppliers', sa.Column('last_score_update', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'last_score_update')
    op.drop_column('suppliers', 'delivery_speed_score')
    op.drop_column('suppliers', 'price_consistency_score')
    # ### end Alembic commands ###
