"""Add UserOnboardingState

Revision ID: 1f21c5e4ffc1
Revises: 75bf8c53b4c5
Create Date: 2026-02-19 17:18:26.319834+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '1f21c5e4ffc1'
down_revision: Union[str, None] = '75bf8c53b4c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_logs_entity_id'), 'event_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_event_logs_event_type'), 'event_logs', ['event_type'], unique=False)
    op.create_table('ledger_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_frozen', sa.Boolean(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('owner_id', 'owner_type', 'account_type', 'currency', name='uq_ledger_account_owner_currency')
    )
    op.create_index(op.f('ix_ledger_accounts_owner_id'), 'ledger_accounts', ['owner_id'], unique=False)
    op.create_table('ledger_transactions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=100), nullable=False),
    sa.Column('reference_type', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('entry_hash', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_transactions_idempotency_key'), 'ledger_transactions', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_ledger_transactions_reference_id'), 'ledger_transactions', ['reference_id'], unique=False)
    op.create_table('notification_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('template_body', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_type')
    )
    op.create_table('intent_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('normalized_product', sa.String(length=255), nullable=True),
    sa.Column('urgency_level', sa.String(length=20), nullable=True),
    sa.Column('expected_qty', sa.Float(), nullable=True),
    sa.Column('captured_from', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_intent_signals_merchant_id'), 'intent_signals', ['merchant_id'], unique=False)
    op.create_table('ledger_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('direction', sa.String(length=10), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("direction IN ('DEBIT', 'CREDIT')", name='check_ledger_entry_direction'),
    sa.CheckConstraint('amount > 0', name='check_ledger_entry_positive_amount'),
    sa.ForeignKeyConstraint(['account_id'], ['ledger_accounts.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['ledger_transactions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ledger_entries_account_id'), 'ledger_entries', ['account_id'], unique=False)
    op.create_index(op.f('ix_ledger_entries_transaction_id'), 'ledger_entries', ['transaction_id'], unique=False)
    op.create_table('risk_decision_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_decision_logs_merchant_id'), 'risk_decision_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_risk_decision_logs_transaction_id'), 'risk_decision_logs', ['transaction_id'], unique=False)
    op.create_table('trigger_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('dedupe_key', sa.String(length=255), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trigger_events_dedupe_key'), 'trigger_events', ['dedupe_key'], unique=False)
    op.create_index(op.f('ix_trigger_events_expires_at'), 'trigger_events', ['expires_at'], unique=False)
    op.create_index(op.f('ix_trigger_events_merchant_id'), 'trigger_events', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_trigger_events_status'), 'trigger_events', ['status'], unique=False)
    op.create_index('ix_triggers_merchant_status_priority', 'trigger_events', ['merchant_id', 'status', 'priority'], unique=False)
    op.create_index('ix_triggers_pending_queue', 'trigger_events', ['status', 'next_retry_at', 'priority', 'created_at'], unique=False)
    op.create_table('user_onboarding_states',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('step', sa.String(length=50), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=True),
    sa.Column('onboarding_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_onboarding_states_merchant_id'), 'user_onboarding_states', ['merchant_id'], unique=True)
    op.create_table('negotiation_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('message_text', sa.Text(), nullable=False),
    sa.Column('intent_detected', sa.String(length=50), nullable=True),
    sa.Column('price_objection', sa.Boolean(), nullable=True),
    sa.Column('credit_request', sa.Boolean(), nullable=True),
    sa.Column('trust_issue', sa.Boolean(), nullable=True),
    sa.Column('delivery_issue', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_signals_merchant_id'), 'negotiation_signals', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_negotiation_signals_trigger_id'), 'negotiation_signals', ['trigger_id'], unique=False)
    op.create_table('notification_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('channel', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_logs_merchant_id'), 'notification_logs', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_notification_logs_trigger_id'), 'notification_logs', ['trigger_id'], unique=False)
    op.create_table('supplier_performance_signals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('delivery_time_days', sa.Float(), nullable=True),
    sa.Column('condition_rating', sa.Integer(), nullable=True),
    sa.Column('accuracy_rating', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_performance_signals_merchant_id'), 'supplier_performance_signals', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_supplier_performance_signals_supplier_id'), 'supplier_performance_signals', ['supplier_id'], unique=False)
    op.create_table('user_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('executed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant_id', 'trigger_id', 'action_type', name='uq_action_idempotency')
    )
    op.create_index(op.f('ix_user_actions_merchant_id'), 'user_actions', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_user_actions_trigger_id'), 'user_actions', ['trigger_id'], unique=False)
    op.create_table('decision_contexts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('trigger_id', sa.UUID(), nullable=True),
    sa.Column('user_action_id', sa.UUID(), nullable=True),
    sa.Column('price_at_time', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('supplier_score', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('credit_available', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['trigger_id'], ['trigger_events.id'], ),
    sa.ForeignKeyConstraint(['user_action_id'], ['user_actions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_action_id')
    )
    op.create_index(op.f('ix_decision_contexts_merchant_id'), 'decision_contexts', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_decision_contexts_trigger_id'), 'decision_contexts', ['trigger_id'], unique=False)
    op.add_column('merchants', sa.Column('preferred_channel', sa.String(length=20), nullable=True))
    op.add_column('merchants', sa.Column('quiet_hours_start', sa.Time(), nullable=True))
    op.add_column('merchants', sa.Column('quiet_hours_end', sa.Time(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('merchants', 'quiet_hours_end')
    op.drop_column('merchants', 'quiet_hours_start')
    op.drop_column('merchants', 'preferred_channel')
    op.drop_index(op.f('ix_decision_contexts_trigger_id'), table_name='decision_contexts')
    op.drop_index(op.f('ix_decision_contexts_merchant_id'), table_name='decision_contexts')
    op.drop_table('decision_contexts')
    op.drop_index(op.f('ix_user_actions_trigger_id'), table_name='user_actions')
    op.drop_index(op.f('ix_user_actions_merchant_id'), table_name='user_actions')
    op.drop_table('user_actions')
    op.drop_index(op.f('ix_supplier_performance_signals_supplier_id'), table_name='supplier_performance_signals')
    op.drop_index(op.f('ix_supplier_performance_signals_merchant_id'), table_name='supplier_performance_signals')
    op.drop_table('supplier_performance_signals')
    op.drop_index(op.f('ix_notification_logs_trigger_id'), table_name='notification_logs')
    op.drop_index(op.f('ix_notification_logs_merchant_id'), table_name='notification_logs')
    op.drop_table('notification_logs')
    op.drop_index(op.f('ix_negotiation_signals_trigger_id'), table_name='negotiation_signals')
    op.drop_index(op.f('ix_negotiation_signals_merchant_id'), table_name='negotiation_signals')
    op.drop_table('negotiation_signals')
    op.drop_index(op.f('ix_user_onboarding_states_merchant_id'), table_name='user_onboarding_states')
    op.drop_table('user_onboarding_states')
    op.drop_index('ix_triggers_pending_queue', table_name='trigger_events')
    op.drop_index('ix_triggers_merchant_status_priority', table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_status'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_merchant_id'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_expires_at'), table_name='trigger_events')
    op.drop_index(op.f('ix_trigger_events_dedupe_key'), table_name='trigger_events')
    op.drop_table('trigger_events')
    op.drop_index(op.f('ix_risk_decision_logs_transaction_id'), table_name='risk_decision_logs')
    op.drop_index(op.f('ix_risk_decision_logs_merchant_id'), table_name='risk_decision_logs')
    op.drop_table('risk_decision_logs')
    op.drop_index(op.f('ix_ledger_entries_transaction_id'), table_name='ledger_entries')
    op.drop_index(op.f('ix_ledger_entries_account_id'), table_name='ledger_entries')
    op.drop_table('ledger_entries')
    op.drop_index(op.f('ix_intent_signals_merchant_id'), table_name='intent_signals')
    op.drop_table('intent_signals')
    op.drop_table('notification_templates')
    op.drop_index(op.f('ix_ledger_transactions_reference_id'), table_name='ledger_transactions')
    op.drop_index(op.f('ix_ledger_transactions_idempotency_key'), table_name='ledger_transactions')
    op.drop_table('ledger_transactions')
    op.drop_index(op.f('ix_ledger_accounts_owner_id'), table_name='ledger_accounts')
    op.drop_table('ledger_accounts')
    op.drop_index(op.f('ix_event_logs_event_type'), table_name='event_logs')
    op.drop_index(op.f('ix_event_logs_entity_id'), table_name='event_logs')
    op.drop_table('event_logs')
    # ### end Alembic commands ###
