"""Add DocArticle model

Revision ID: a0d68db26ea4
Revises: 1f21c5e4ffc1
Create Date: 2026-02-19 17:37:03.717742+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0d68db26ea4'
down_revision: Union[str, None] = '1f21c5e4ffc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('doc_articles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_doc_articles_category_order', 'doc_articles', ['category', 'order_index'], unique=False)
    op.create_index(op.f('ix_doc_articles_slug'), 'doc_articles', ['slug'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_doc_articles_slug'), table_name='doc_articles')
    op.drop_index('ix_doc_articles_category_order', table_name='doc_articles')
    op.drop_table('doc_articles')
    # ### end Alembic commands ###
