"""add_pharma_columns

Revision ID: e29b0bef1f91
Revises: 7ae2b2d05c24
Create Date: 2026-02-18 23:06:52.636078+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e29b0bef1f91'
down_revision: Union[str, None] = '7ae2b2d05c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('batch_number', sa.String(length=50), nullable=True))
    op.add_column('invoice_items', sa.Column('expiry_date', sa.Date(), nullable=True))
    op.add_column('invoice_items', sa.Column('hsn_code', sa.String(length=20), nullable=True))
    op.add_column('invoice_items', sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'mrp')
    op.drop_column('invoice_items', 'hsn_code')
    op.drop_column('invoice_items', 'expiry_date')
    op.drop_column('invoice_items', 'batch_number')
    # ### end Alembic commands ###
