"""add network intelligence tables

Revision ID: ac826f6f4e96
Revises: 635481ac630d
Create Date: 2026-02-15 09:36:34.551027+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac826f6f4e96'
down_revision: Union[str, None] = '635481ac630d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('risk_alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('aggregated_prices',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('time_window', sa.DateTime(timezone=True), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('median_price', sa.Float(), nullable=True),
    sa.Column('p25_price', sa.Float(), nullable=True),
    sa.Column('p75_price', sa.Float(), nullable=True),
    sa.Column('volatility', sa.Float(), nullable=True),
    sa.Column('data_points', sa.Integer(), nullable=True),
    sa.Column('merchant_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aggregated_prices_city'), 'aggregated_prices', ['city'], unique=False)
    op.create_index(op.f('ix_aggregated_prices_product_id'), 'aggregated_prices', ['product_id'], unique=False)
    op.create_index(op.f('ix_aggregated_prices_time_window'), 'aggregated_prices', ['time_window'], unique=False)
    op.create_table('market_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('trend_type', sa.String(length=50), nullable=True),
    sa.Column('direction', sa.String(length=10), nullable=True),
    sa.Column('magnitude', sa.Float(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_trends_city'), 'market_trends', ['city'], unique=False)
    op.create_index(op.f('ix_market_trends_product_id'), 'market_trends', ['product_id'], unique=False)
    op.create_table('supplier_benchmarks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('price_competitiveness', sa.Float(), nullable=True),
    sa.Column('delivery_reliability', sa.Float(), nullable=True),
    sa.Column('fulfillment_accuracy', sa.Float(), nullable=True),
    sa.Column('merchant_retention', sa.Float(), nullable=True),
    sa.Column('network_rank', sa.Integer(), nullable=True),
    sa.Column('total_suppliers_in_region', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_benchmarks_city'), 'supplier_benchmarks', ['city'], unique=False)
    op.create_index(op.f('ix_supplier_benchmarks_supplier_id'), 'supplier_benchmarks', ['supplier_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_supplier_benchmarks_supplier_id'), table_name='supplier_benchmarks')
    op.drop_index(op.f('ix_supplier_benchmarks_city'), table_name='supplier_benchmarks')
    op.drop_table('supplier_benchmarks')
    op.drop_index(op.f('ix_market_trends_product_id'), table_name='market_trends')
    op.drop_index(op.f('ix_market_trends_city'), table_name='market_trends')
    op.drop_table('market_trends')
    op.drop_index(op.f('ix_aggregated_prices_time_window'), table_name='aggregated_prices')
    op.drop_index(op.f('ix_aggregated_prices_product_id'), table_name='aggregated_prices')
    op.drop_index(op.f('ix_aggregated_prices_city'), table_name='aggregated_prices')
    op.drop_table('aggregated_prices')
    op.drop_table('risk_alerts')
    # ### end Alembic commands ###
