"""create_market_index

Revision ID: 7ae2b2d05c24
Revises: 134effb9f182
Create Date: 2026-02-18 22:50:20.905451+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ae2b2d05c24'
down_revision: Union[str, None] = '134effb9f182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_index',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('normalized_product_name', sa.String(length=255), nullable=False),
    sa.Column('product_category', sa.String(length=100), nullable=True),
    sa.Column('avg_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('min_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('region', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_index_normalized_product_name'), 'market_index', ['normalized_product_name'], unique=True)
    op.create_index(op.f('ix_market_index_product_category'), 'market_index', ['product_category'], unique=False)
    op.create_index(op.f('ix_market_index_region'), 'market_index', ['region'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_index_region'), table_name='market_index')
    op.drop_index(op.f('ix_market_index_product_category'), table_name='market_index')
    op.drop_index(op.f('ix_market_index_normalized_product_name'), table_name='market_index')
    op.drop_table('market_index')
    # ### end Alembic commands ###
