"""add learning system tables

Revision ID: 635481ac630d
Revises: 
Create Date: 2026-02-15 09:31:53.810504+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635481ac630d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_activity_logs_action', table_name='activity_logs')
    op.drop_index('idx_activity_logs_actor_id', table_name='activity_logs')
    op.drop_index('idx_activity_logs_created_at', table_name='activity_logs')
    op.drop_index('idx_activity_logs_resource_type', table_name='activity_logs')
    op.create_index(op.f('ix_activity_logs_action'), 'activity_logs', ['action'], unique=False)
    op.create_index(op.f('ix_activity_logs_actor_id'), 'activity_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_activity_logs_resource_type'), 'activity_logs', ['resource_type'], unique=False)
    op.drop_index('idx_invoice_items_invoice_id', table_name='invoice_items')
    op.drop_index('idx_invoice_items_product_id', table_name='invoice_items')
    op.create_index(op.f('ix_invoice_items_invoice_id'), 'invoice_items', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_invoice_items_product_id'), 'invoice_items', ['product_id'], unique=False)
    op.create_index('ix_invoice_items_product_invoice', 'invoice_items', ['product_id', 'invoice_id'], unique=False)
    op.drop_index('idx_invoices_created_at', table_name='invoices')
    op.drop_index('idx_invoices_merchant_id', table_name='invoices')
    op.drop_index('idx_invoices_ocr_status', table_name='invoices')
    op.drop_index('idx_invoices_supplier_id', table_name='invoices')
    op.create_index(op.f('ix_invoices_merchant_id'), 'invoices', ['merchant_id'], unique=False)
    op.create_index('ix_invoices_merchant_status', 'invoices', ['merchant_id', 'ocr_status'], unique=False)
    op.create_index(op.f('ix_invoices_supplier_id'), 'invoices', ['supplier_id'], unique=False)
    op.drop_index('idx_merchants_city', table_name='merchants')
    op.drop_index('idx_merchants_email', table_name='merchants')
    op.drop_index('idx_merchants_is_active', table_name='merchants')
    op.drop_index('idx_merchants_role', table_name='merchants')
    op.drop_constraint('merchants_email_key', 'merchants', type_='unique')
    op.create_index(op.f('ix_merchants_email'), 'merchants', ['email'], unique=True)
    op.drop_index('idx_products_category', table_name='products')
    op.drop_index('idx_products_normalized_name', table_name='products')
    op.drop_index('idx_products_sku_code', table_name='products')
    op.drop_constraint('products_sku_code_key', 'products', type_='unique')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.create_index(op.f('ix_products_normalized_name'), 'products', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_products_sku_code'), 'products', ['sku_code'], unique=True)
    op.drop_index('idx_recommendations_merchant_id', table_name='recommendations')
    op.drop_index('idx_recommendations_status', table_name='recommendations')
    op.create_index(op.f('ix_recommendations_merchant_id'), 'recommendations', ['merchant_id'], unique=False)
    op.drop_index('idx_scores_merchant_id', table_name='scores')
    op.drop_index('idx_scores_supplier_id', table_name='scores')
    op.drop_index('idx_scores_total_score', table_name='scores')
    op.create_index(op.f('ix_scores_merchant_id'), 'scores', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_scores_supplier_id'), 'scores', ['supplier_id'], unique=False)
    op.alter_column('suppliers', 'credit_terms',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('idx_suppliers_category', table_name='suppliers')
    op.drop_index('idx_suppliers_city', table_name='suppliers')
    op.drop_index('idx_suppliers_is_approved', table_name='suppliers')
    op.drop_index('idx_suppliers_name', table_name='suppliers')
    op.create_index(op.f('ix_suppliers_category'), 'suppliers', ['category'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.drop_index('idx_whatsapp_messages_merchant_id', table_name='whatsapp_messages')
    op.drop_index('idx_whatsapp_messages_phone', table_name='whatsapp_messages')
    op.create_index(op.f('ix_whatsapp_messages_merchant_id'), 'whatsapp_messages', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_whatsapp_messages_phone_number'), 'whatsapp_messages', ['phone_number'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whatsapp_messages_phone_number'), table_name='whatsapp_messages')
    op.drop_index(op.f('ix_whatsapp_messages_merchant_id'), table_name='whatsapp_messages')
    op.create_index('idx_whatsapp_messages_phone', 'whatsapp_messages', ['phone_number'], unique=False)
    op.create_index('idx_whatsapp_messages_merchant_id', 'whatsapp_messages', ['merchant_id'], unique=False)
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_category'), table_name='suppliers')
    op.create_index('idx_suppliers_name', 'suppliers', ['name'], unique=False)
    op.create_index('idx_suppliers_is_approved', 'suppliers', ['is_approved'], unique=False)
    op.create_index('idx_suppliers_city', 'suppliers', ['city'], unique=False)
    op.create_index('idx_suppliers_category', 'suppliers', ['category'], unique=False)
    op.alter_column('suppliers', 'credit_terms',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index(op.f('ix_scores_supplier_id'), table_name='scores')
    op.drop_index(op.f('ix_scores_merchant_id'), table_name='scores')
    op.create_index('idx_scores_total_score', 'scores', [sa.text('total_score DESC')], unique=False)
    op.create_index('idx_scores_supplier_id', 'scores', ['supplier_id'], unique=False)
    op.create_index('idx_scores_merchant_id', 'scores', ['merchant_id'], unique=False)
    op.drop_index(op.f('ix_recommendations_merchant_id'), table_name='recommendations')
    op.create_index('idx_recommendations_status', 'recommendations', ['status'], unique=False)
    op.create_index('idx_recommendations_merchant_id', 'recommendations', ['merchant_id'], unique=False)
    op.drop_index(op.f('ix_products_sku_code'), table_name='products')
    op.drop_index(op.f('ix_products_normalized_name'), table_name='products')
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_unique_constraint('products_sku_code_key', 'products', ['sku_code'])
    op.create_index('idx_products_sku_code', 'products', ['sku_code'], unique=False)
    op.create_index('idx_products_normalized_name', 'products', ['normalized_name'], unique=False)
    op.create_index('idx_products_category', 'products', ['category'], unique=False)
    op.drop_index(op.f('ix_merchants_email'), table_name='merchants')
    op.create_unique_constraint('merchants_email_key', 'merchants', ['email'])
    op.create_index('idx_merchants_role', 'merchants', ['role'], unique=False)
    op.create_index('idx_merchants_is_active', 'merchants', ['is_active'], unique=False)
    op.create_index('idx_merchants_email', 'merchants', ['email'], unique=False)
    op.create_index('idx_merchants_city', 'merchants', ['city'], unique=False)
    op.drop_index(op.f('ix_invoices_supplier_id'), table_name='invoices')
    op.drop_index('ix_invoices_merchant_status', table_name='invoices')
    op.drop_index(op.f('ix_invoices_merchant_id'), table_name='invoices')
    op.create_index('idx_invoices_supplier_id', 'invoices', ['supplier_id'], unique=False)
    op.create_index('idx_invoices_ocr_status', 'invoices', ['ocr_status'], unique=False)
    op.create_index('idx_invoices_merchant_id', 'invoices', ['merchant_id'], unique=False)
    op.create_index('idx_invoices_created_at', 'invoices', ['created_at'], unique=False)
    op.drop_index('ix_invoice_items_product_invoice', table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_product_id'), table_name='invoice_items')
    op.drop_index(op.f('ix_invoice_items_invoice_id'), table_name='invoice_items')
    op.create_index('idx_invoice_items_product_id', 'invoice_items', ['product_id'], unique=False)
    op.create_index('idx_invoice_items_invoice_id', 'invoice_items', ['invoice_id'], unique=False)
    op.drop_index(op.f('ix_activity_logs_resource_type'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_actor_id'), table_name='activity_logs')
    op.drop_index(op.f('ix_activity_logs_action'), table_name='activity_logs')
    op.create_index('idx_activity_logs_resource_type', 'activity_logs', ['resource_type'], unique=False)
    op.create_index('idx_activity_logs_created_at', 'activity_logs', [sa.text('created_at DESC')], unique=False)
    op.create_index('idx_activity_logs_actor_id', 'activity_logs', ['actor_id'], unique=False)
    op.create_index('idx_activity_logs_action', 'activity_logs', ['action'], unique=False)
    # ### end Alembic commands ###
